<a href="https://colab.research.google.com/github/adilnarakkoden1/datasciencelab/blob/main/adiloutcome1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
abc = np.array ([1,2,3,4,5,6,7,8,9,10])
print(abc)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
import numpy as np
abc = np.array ([1])
print(abc)

[1]


In [ ]:
import numpy as np
abc =  ([1,2])
np.ones(abc)

array([[1., 1.]])

In [ ]:
import numpy as np
np.zeros(2,2)

TypeError: ignored

In [ ]:
import numpy as np
abc =  ([1,2])
np.zeros(abc)

array([[0., 0.]])

In [ ]:
import numpy as np
abc = np.eye (2, dtype=int)
print(abc)

[[1 0]
 [0 1]]


In [ ]:
import numpy as np
abc = np.eye (4,5)
print(abc)


In [ ]:
import numpy as np
np.arange (5)


array([0, 1, 2, 3, 4])

In [ ]:
import numpy as np
a1 =np.array([2,4,5,6])
a2 =np.array([1,5,8,7])
a3=a1+a2
print(a3)

[ 3  9 13 13]


In [ ]:
import numpy as np
a1 =np.array([2,4,5,6])
a2 =np.array([1,5,8,7])
a3=a1-a2
print(a3)

[ 1 -1 -3 -1]


In [ ]:
import numpy as np
a1 =np.array([2,4,5,6])
a2 =np.array([1,5,8,7])
a3=a1*a2
print(a3)

[ 2 20 40 42]


In [ ]:
import numpy as np
a1 =np.array([2,4,5,6])
a2 =np.array([1,5,8,7])
a3=a1/a2
print(a3)

[2.         0.8        0.625      0.85714286]


In [ ]:
import numpy as np
a1 =np.array([2,4,5,6])
a1=a1**2
print(a1)

[ 4 16 25 36]


In [ ]:
import numpy as np
a1 =np.array([1,2,4,5,6,7])
a2 =a1.reshape([2,3])
print(a2)

[[1 2 4]
 [5 6 7]]


In [ ]:
import numpy as np
a1 =np.array([1,2,4,5,6,7])
a1.resize([2,3])
print(a1)

[[1 2 4]
 [5 6 7]]


In [ ]:
import numpy as np
np.linspace(1,2, num=5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
import numpy as np
ar = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(ar)
a,b,c=np.linalg.svd(ar)
print("\n=",a,"\n=b",b,"\n=c",c)



  

[[1 2 3]
 [4 5 6]
 [7 8 9]]

= [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]] 
=b [1.68481034e+01 1.06836951e+00 3.33475287e-16] 
=c [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]
